---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wuxin.
--- DateTime: 2019-11-12 13:50
---

local http = require("socket.http")
local resp = http.request("http://www.baidu.com")
print(resp)