---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wuxin.
--- DateTime: 2019-11-14 18:13
---
local typedefs = require "kong.db.schema.typedefs"


return {
    name = "myplugin",
    fields = {
        { consumer = typedefs.no_consumer },
        { run_on = typedefs.run_on_first },
        { protocols = typedefs.protocols_http },
        { config = {
            type = "record",
            fields = {
                { myconf = { type = "string", uuid = true, legacy = true }, },

            }, }, },
    },
}